import '../styles/globals.css';
import '@rainbow-me/rainbowkit/styles.css';
import type { AppProps } from 'next/app';

import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { WagmiProvider } from 'wagmi';
import { RainbowKitProvider } from '@rainbow-me/rainbowkit';

import { config } from '../wagmi';
import Head from "next/head";
import PageHeader from "../components/page-header";
import GlobalScan from "../components/page-halo-animation";
import CyberBackground from "../components/cyber-background";
import CyberAnimations from "../components/cyber-animations";
import CenterGuang from "../components/center-guang";

const client = new QueryClient();

function MyApp({ Component, pageProps }: AppProps) {
  return <>
      <Head>
          <title>RainbowKit App</title>
          <meta
              content="Generated by @rainbow-me/create-rainbowkit"
              name="description"
          />
          <link href="/favicon.ico" rel="icon" />
      </Head>
      <WagmiProvider config={config}>
          <QueryClientProvider client={client}>
              <RainbowKitProvider>
                  <div className="p-x-2 flex flex-col min-h-screen">
                      <CyberBackground/>
                      <div className={"fixed w-[1000px] h-[1000px] bottom-0 right-0"}>
                          <CenterGuang/>
                      </div>
                      <div className="relative z-10 flex-1">
                          <PageHeader/>
                          <div className="flex-1">
                              <Component {...pageProps} />
                          </div>
                      </div>
                      <footer className={"flex py-4 border-t-1 border-gray-200 text-gray-100 justify-center items-center"}>
                          <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
                              Made with ❤️ by your frens at 🌈
                          </a>
                      </footer>
                      {/*扫描线背景层 */}
                      {/*<GlobalScan/>*/}
                      {/* 第3层：轻量动画（CSS） */}
                      <CyberAnimations />
                  </div>
              </RainbowKitProvider>
          </QueryClientProvider>
      </WagmiProvider>
  </>
}

export default MyApp;
